spring: 
  redis:
    database: 0
    conf:
      type: Standalone     
    host: "${REDIS_HOSTNAME}"
    jedis: 
      pool: 
        max-active: 10
        max-idle: 50
        max-wait: 10
        min-idle: 16
        time-to-live: "minutes:100"
    password: "${REDIS_PASSWORD}"
    port: "${REDIS_PORT}"
    timeout: 10